"use client";
import { ChangeEvent, useEffect, useState } from "react";
type Comment = { id?: string; html: string; plainText: string };
type Item = { id?: string; title: string; comments: Comment[] };
type Section = { id?: string; title: string; items: Item[] };
type Template = { id: string; name: string; sourceFilename: string; sections?: Section[]; imports?: { stats: { sections: number; items: number; comments: number }; warnings: string[]; sourceSha256: string }[] };
const clone = <T,>(x: T): T => JSON.parse(JSON.stringify(x));
export default function Home() {
  const [templates, setTemplates] = useState<Template[]>([]), [active, setActive] = useState<Template | null>(null), [file, setFile] = useState<File | null>(null), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const load = async () => { const data = await (await fetch("/api/templates")).json(); setTemplates(data); if (!active && data[0]) open(data[0].id); };
  const open = async (id: string) => { setActive(await (await fetch(`/api/templates/${id}`)).json()); setNotice(""); };
  useEffect(() => { load(); }, []);
  const importFile = async () => { if (!file) return setNotice("Choose a Spectora HTML-text export to import."); setBusy(true); const form = new FormData(); form.append("file", file); const r = await fetch("/api/templates", { method: "POST", body: form }); const data = await r.json(); setBusy(false); if (!r.ok) return setNotice(data.error); setNotice(`Imported ${data.stats.sections} sections, ${data.stats.items} items, and ${data.stats.comments} comments.`); await load(); await open(data.template.id); };
  const edit = (fn: (t: Template) => void) => { if (!active) return; const next = clone(active); fn(next); setActive(next); };
  const save = async () => { if (!active?.sections) return; setBusy(true); const r = await fetch(`/api/templates/${active.id}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: active.name, sections: active.sections }) }); setBusy(false); setNotice(r.ok ? "Saved to the database." : "Save failed. Your edits remain on screen."); if (r.ok) load(); };
  const duplicate = async () => { if (!active) return; setBusy(true); const r = await fetch(`/api/templates/${active.id}/duplicate`, { method: "POST" }); const data = await r.json(); setBusy(false); if (r.ok) { await load(); await open(data.id); setNotice("Created an independent copy."); } };
  return <main><header><div><p className="eyebrow">MigrateKit</p><h1>Keep the template work that took years.</h1><p className="sub">Import a Spectora HTML-text export into a structured, editable inspection template.</p></div><button className="primary" onClick={save} disabled={!active || busy}>Save changes</button></header>
    <section className="import"><div><strong>Import a template</strong><span>HTML-text export · 5 MB max · hierarchy and source HTML retained</span></div><input type="file" accept=".html,.htm,text/html" onChange={(e: ChangeEvent<HTMLInputElement>) => setFile(e.target.files?.[0] ?? null)} /><button onClick={importFile} disabled={busy}>{busy ? "Working…" : "Import"}</button></section>
    {notice && <p className="notice">{notice}</p>}
    <div className="layout"><aside><p className="eyebrow">Templates</p>{templates.length === 0 && <p className="muted">No templates yet. Import the supplied sample to begin.</p>}{templates.map(t => <button className={active?.id === t.id ? "template selected" : "template"} key={t.id} onClick={() => open(t.id)}><strong>{t.name}</strong><small>{t.sourceFilename}</small></button>)}</aside>
      <section className="editor">{!active ? <div className="empty"><h2>Start with an export</h2><p>Every imported piece is represented as a section, item, or comment—not one opaque document.</p></div> : <><div className="editorTop"><input className="title" value={active.name} onChange={e => edit(t => t.name = e.target.value)} /><button onClick={duplicate} disabled={busy}>Duplicate template</button></div>
        {active.imports?.[0] && <details className="audit"><summary>Import receipt · {active.imports[0].stats.sections} sections / {active.imports[0].stats.items} items / {active.imports[0].stats.comments} comments</summary><p>Source fingerprint: <code>{active.imports[0].sourceSha256.slice(0, 16)}…</code></p>{active.imports[0].warnings.map((w, i) => <p key={i} className="warning">⚠ {w}</p>)}</details>}
        {active.sections?.map((section, si) => <article className="section" key={section.id ?? si}><input value={section.title} aria-label="Section name" onChange={e => edit(t => t.sections![si].title = e.target.value)} />{section.items.map((item, ii) => <div className="item" key={item.id ?? ii}><input value={item.title} aria-label="Item name" onChange={e => edit(t => t.sections![si].items[ii].title = e.target.value)} />{item.comments.map((comment, ci) => <textarea key={comment.id ?? ci} value={comment.plainText} aria-label="Comment text" onChange={e => edit(t => { const c = t.sections![si].items[ii].comments[ci]; c.plainText = e.target.value; c.html = `<p>${e.target.value.replace(/</g, "&lt;")}</p>`; })} />)}</div>)}</article>)}</>}</section></div>
    <footer><strong>Honest import:</strong> links and inline HTML are retained per comment; the editor currently presents plain text. Missing photos, ratings, and form rules cannot be reconstructed from the HTML-text export. Unsupported embedded media is called out in the receipt.</footer>
  </main>;
}
