import { createHash } from "crypto";
import * as XLSX from "xlsx";

export type ImportedComment = { html: string; plainText: string };
export type ImportedItem = { title: string; comments: ImportedComment[] };
export type ImportedSection = { title: string; items: ImportedItem[] };
export type ImportResult = { sections: ImportedSection[]; warnings: string[]; sha256: string; stats: { sections: number; items: number; comments: number } };

const text = (html: string) => html.replace(/<br\s*\/?/gi, "\n").replace(/<[^>]+>/g, " ").replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/\s+/g, " ").trim();
const blocks = (html: string) => html.match(/<(h[1-6]|p|li|div|td)[^>]*>[\s\S]*?<\/\1>/gi) ?? [];
const tag = (block: string) => /^<([a-z0-9]+)/i.exec(block)?.[1].toLowerCase() ?? "";

/** Parses the semantic hierarchy in a Spectora HTML-text export without using an LLM. */
export function parseSpectoraHtml(raw: string): ImportResult {
  const warnings: string[] = [];
  const sections: ImportedSection[] = [];
  let section: ImportedSection | undefined;
  let item: ImportedItem | undefined;
  const addSection = (title: string) => { section = { title, items: [] }; sections.push(section); item = undefined; };
  const addItem = (title: string) => { if (!section) addSection("Imported content"); item = { title, comments: [] }; section!.items.push(item); };
  for (const block of blocks(raw)) {
    const value = text(block); if (!value) continue;
    const kind = tag(block);
    if (kind === "h1" || kind === "h2") { addSection(value); continue; }
    if (kind === "h3" || kind === "h4") { addItem(value); continue; }
    if (!item && (kind === "li" || kind === "td")) { addItem(value); continue; }
    if (!item) { warnings.push(`Unattached content preserved in an “Imported content” item: ${value.slice(0, 80)}`); addItem("Imported content"); }
    item!.comments.push({ html: block, plainText: value });
  }
  if (!sections.length) throw new Error("No supported HTML content was found. Upload the HTML-text export, not a PDF or regular report.");
  const comments = sections.flatMap(s => s.items).reduce((n, i) => n + i.comments.length, 0);
  const items = sections.reduce((n, s) => n + s.items.length, 0);
  if (!items) warnings.push("Headings were found, but no item-level headings were present. Add items in the editor.");
  if (/<(img|table|iframe|script|style)\b/i.test(raw)) warnings.push("The source contains media, tables, or embedded content. It is retained in comment HTML where possible, but not rendered as a dedicated field.");
  return { sections, warnings, sha256: createHash("sha256").update(raw).digest("hex"), stats: { sections: sections.length, items, comments } };
}

const normalized = (value: unknown) => String(value ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const htmlFromCell = (cell: XLSX.CellObject | undefined) => cell?.h || String(cell?.w ?? cell?.v ?? "");

/**
 * Imports the spreadsheet generated by Spectora's “Export to spreadsheet →
 * Export HTML Text” option. The export shape differs by account/version, so
 * this uses labeled columns when available and retains unrecognised columns as
 * visible comments rather than silently dropping them.
 */
export function parseSpectoraSpreadsheet(bytes: Buffer): ImportResult {
  const workbook = XLSX.read(bytes, { type: "buffer", cellHTML: true });
  if (!workbook.SheetNames.length) throw new Error("The spreadsheet has no worksheets.");
  const sheet = workbook.Sheets[workbook.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: "", raw: false });
  const nonEmptyRows = rows.filter(row => row.some(cell => String(cell).trim()));
  if (!nonEmptyRows.length) throw new Error("The spreadsheet is empty.");
  const headerIndex = nonEmptyRows.findIndex(row => row.some(cell => /section|category|component|item|comment|html|description/i.test(String(cell))));
  const warnings: string[] = [];
  const sections: ImportedSection[] = [];
  let section: ImportedSection | undefined;
  let item: ImportedItem | undefined;
  const addSection = (title: string) => { section = { title, items: [] }; sections.push(section); item = undefined; };
  const addItem = (title: string) => { if (!section) addSection("Imported content"); item = { title, comments: [] }; section!.items.push(item); };
  const headers = headerIndex >= 0 ? nonEmptyRows[headerIndex].map(normalized) : [];
  const column = (...terms: string[]) => headers.findIndex(header => terms.some(term => header === term || header.includes(term)));
  const sectionColumn = column("section", "category", "component");
  const itemColumn = column("item", "inspection item", "name");
  const commentColumns = headers.map((header, index) => /comment|html|description|text|note/.test(header) ? index : -1).filter(index => index >= 0);
  const start = headerIndex >= 0 ? headerIndex + 1 : 0;
  for (let rowIndex = start; rowIndex < nonEmptyRows.length; rowIndex++) {
    const row = nonEmptyRows[rowIndex];
    const values = row.map(value => String(value).trim());
    const sectionName = sectionColumn >= 0 ? values[sectionColumn] : "";
    const itemName = itemColumn >= 0 ? values[itemColumn] : "";
    if (sectionName && (!section || section.title !== sectionName)) addSection(sectionName);
    if (itemName) addItem(itemName);
    const candidates = (commentColumns.length ? commentColumns : values.map((_, index) => index))
      .filter(index => index !== sectionColumn && index !== itemColumn)
      .map(index => ({ index, text: values[index] }))
      .filter(value => value.text);
    if (!candidates.length) continue;
    if (!item) { addItem(itemName || `Row ${rowIndex + 1}`); warnings.push(`Row ${rowIndex + 1} had content without a recognized item; it was preserved as its own item.`); }
    for (const candidate of candidates) {
      const cellAddress = XLSX.utils.encode_cell({ r: rowIndex, c: candidate.index });
      const html = htmlFromCell(sheet[cellAddress]) || candidate.text;
      item!.comments.push({ html, plainText: text(html) || candidate.text });
    }
  }
  if (!sections.length) {
    const fallbackHtml = nonEmptyRows.flat().map(value => String(value)).filter(Boolean).join("\n");
    warnings.push("No section/item columns were recognized. All non-empty cells were preserved under Imported content.");
    return { ...parseSpectoraHtml(`<h1>Imported content</h1><h3>Spreadsheet content</h3><p>${fallbackHtml.replace(/</g, "&lt;")}</p>`), warnings, sha256: createHash("sha256").update(bytes).digest("hex") };
  }
  const items = sections.reduce((count, value) => count + value.items.length, 0);
  const comments = sections.flatMap(value => value.items).reduce((count, value) => count + value.comments.length, 0);
  if (!commentColumns.length) warnings.push("No dedicated comment column was recognized. Non-hierarchy cells were retained as comments.");
  return { sections, warnings, sha256: createHash("sha256").update(bytes).digest("hex"), stats: { sections: sections.length, items, comments } };
}
